version: 2.1

executors:
  maven-executor:
    docker:
      - image: opennms/maven:jdk8_3.6.1

workflows:
  # Run build-jobs for all branches and any tag
  build-jobs:
    jobs:
      - build

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Build configuration module
          command: |
            mvn install
      - store_artifacts:
          path: ./plugin/target/netsnmp-plugin-1.0.0-SNAPSHOT.jar
          destination: net-snmp-plugin.jar
